name: freelingo
description: Free language learning 
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  appinio_swiper: ^2.1.0
  audio_video_progress_bar: ^2.0.1
  auto_route: 7.8.0
  bloc: ^8.1.2
  cloud_firestore: ^4.13.3
  dropdown_button2: ^2.3.9
  file_picker: ^5.5.0
  firebase_auth: ^4.10.1
  firebase_core: ^2.17.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.7
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  google_sign_in: ^6.1.5
  image_picker: ^1.0.4
  injectable: ^2.3.2
  intl: ^0.18.0
  learning_translate: ^0.0.4
  rive: ^0.12.3
  settings_ui: ^2.0.2
  video_player: ^2.7.2

dev_dependencies:
  auto_route_generator: ^7.3.1
  bloc_test: ^9.1.4
  build_runner: ^2.4.6
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  injectable_generator: ^2.4.1
  mocktail: ^1.0.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/subtitles.srt
    - assets/icons/
    - assets/animations/