// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbDrklzLa8wCwA1w5xpizsBmK1Vsj9yQI',
    appId: '1:703312883161:web:040ae6a659e699df92fdc8',
    messagingSenderId: '703312883161',
    projectId: 'freelingo-dev',
    authDomain: 'freelingo-dev.firebaseapp.com',
    storageBucket: 'freelingo-dev.appspot.com',
    measurementId: 'G-J1ESC6H7FG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDee2XNeNt3C-8kcguL8KDbIESE3OgiU0g',
    appId: '1:703312883161:android:88149190ad01afc892fdc8',
    messagingSenderId: '703312883161',
    projectId: 'freelingo-dev',
    storageBucket: 'freelingo-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFTBQtU2VUbEQOCaQ1u_PuNw_pCA_gOyg',
    appId: '1:703312883161:ios:47cdadbfc4db4efc92fdc8',
    messagingSenderId: '703312883161',
    projectId: 'freelingo-dev',
    storageBucket: 'freelingo-dev.appspot.com',
    iosBundleId: 'com.freelingo.org.freelingo',
  );
}
